
package turismouyapp.webservices;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ActivityPortType", targetNamespace = "http://ws.turismouyapp/schema")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActivityPortType {


    /**
     * 
     * @param nickname
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "activityNames", targetNamespace = "")
    @RequestWrapper(localName = "listTouristActivitiesBySupplierNickname", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivitiesBySupplierNickname")
    @ResponseWrapper(localName = "listTouristActivitiesBySupplierNicknameResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivitiesBySupplierNicknameResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivitiesBySupplierNicknameRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivitiesBySupplierNicknameResponse")
    public List<String> listTouristActivitiesBySupplierNickname(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname);

    /**
     * 
     * @param nickname
     * @return
     *     returns java.util.List<turismouyapp.webservices.DtActivityWithOutings>
     * @throws ActivityDoesNotExistException
     */
    @WebMethod
    @WebResult(name = "DtActivityWithOutings", targetNamespace = "")
    @RequestWrapper(localName = "arrayListTouristActivitiesBySupplierNickName", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ArrayListTouristActivitiesBySupplierNickName")
    @ResponseWrapper(localName = "arrayListTouristActivitiesBySupplierNickNameResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ArrayListTouristActivitiesBySupplierNickNameResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/arrayListTouristActivitiesBySupplierNickNameRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/arrayListTouristActivitiesBySupplierNickNameResponse", fault = {
        @FaultAction(className = ActivityDoesNotExistException.class, value = "http://ws.turismouyapp/schema/ActivityPortType/arrayListTouristActivitiesBySupplierNickName/Fault/ActivityDoesNotExistException")
    })
    public List<DtActivityWithOutings> arrayListTouristActivitiesBySupplierNickName(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname)
        throws ActivityDoesNotExistException
    ;

    /**
     * 
     * @param dtTouristActivity
     */
    @WebMethod
    @RequestWrapper(localName = "modifyActivity", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ModifyActivity")
    @ResponseWrapper(localName = "modifyActivityResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ModifyActivityResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/modifyActivityRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/modifyActivityResponse")
    public void modifyActivity(
        @WebParam(name = "dtTouristActivity", targetNamespace = "")
        DtTouristActivity dtTouristActivity);

    /**
     * 
     * @param dtTouristActivity
     * @throws ActivityDoesNotExistException
     * @throws RepeatedActivityNameException
     */
    @WebMethod
    @RequestWrapper(localName = "activityDataEntry", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ActivityDataEntry")
    @ResponseWrapper(localName = "activityDataEntryResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ActivityDataEntryResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/activityDataEntryRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/activityDataEntryResponse", fault = {
        @FaultAction(className = ActivityDoesNotExistException.class, value = "http://ws.turismouyapp/schema/ActivityPortType/activityDataEntry/Fault/ActivityDoesNotExistException"),
        @FaultAction(className = RepeatedActivityNameException.class, value = "http://ws.turismouyapp/schema/ActivityPortType/activityDataEntry/Fault/RepeatedActivityNameException")
    })
    public void activityDataEntry(
        @WebParam(name = "dtTouristActivity", targetNamespace = "")
        DtTouristActivity dtTouristActivity)
        throws ActivityDoesNotExistException, RepeatedActivityNameException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ActivityDoesNotExistException
     */
    @WebMethod
    @WebResult(name = "activityNames", targetNamespace = "")
    @RequestWrapper(localName = "listTouristActivities", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivities")
    @ResponseWrapper(localName = "listTouristActivitiesResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivitiesResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivitiesRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivitiesResponse", fault = {
        @FaultAction(className = ActivityDoesNotExistException.class, value = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivities/Fault/ActivityDoesNotExistException")
    })
    public List<String> listTouristActivities()
        throws ActivityDoesNotExistException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<turismouyapp.webservices.DtActivityWithOutings>
     * @throws ActivityDoesNotExistException
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "listTouristActivityData", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivityData")
    @ResponseWrapper(localName = "listTouristActivityDataResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivityDataResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivityDataRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivityDataResponse", fault = {
        @FaultAction(className = ActivityDoesNotExistException.class, value = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivityData/Fault/ActivityDoesNotExistException")
    })
    public List<DtActivityWithOutings> listTouristActivityData()
        throws ActivityDoesNotExistException
    ;

    /**
     * 
     * @param status
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "activityNames", targetNamespace = "")
    @RequestWrapper(localName = "listTouristActivitiesByStatus", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivitiesByStatus")
    @ResponseWrapper(localName = "listTouristActivitiesByStatusResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListTouristActivitiesByStatusResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivitiesByStatusRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/listTouristActivitiesByStatusResponse")
    public List<String> listTouristActivitiesByStatus(
        @WebParam(name = "status", targetNamespace = "")
        TouristActivityStatus status);

    /**
     * 
     * @param activityName
     * @return
     *     returns turismouyapp.webservices.DtActivityWithOutings
     * @throws ActivityDoesNotExistException
     */
    @WebMethod
    @WebResult(name = "DtActivityWithOutings", targetNamespace = "")
    @RequestWrapper(localName = "consultTouristActivityData", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultTouristActivityData")
    @ResponseWrapper(localName = "consultTouristActivityDataResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultTouristActivityDataResponse")
    @Action(input = "http://ws.turismouyapp/schema/ActivityPortType/consultTouristActivityDataRequest", output = "http://ws.turismouyapp/schema/ActivityPortType/consultTouristActivityDataResponse", fault = {
        @FaultAction(className = ActivityDoesNotExistException.class, value = "http://ws.turismouyapp/schema/ActivityPortType/consultTouristActivityData/Fault/ActivityDoesNotExistException")
    })
    public DtActivityWithOutings consultTouristActivityData(
        @WebParam(name = "activityName", targetNamespace = "")
        String activityName)
        throws ActivityDoesNotExistException
    ;

}
