
package turismouyapp.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ActivityService", targetNamespace = "http://ws.turismouyapp/schema", wsdlLocation = "http://localhost:8007/ws/activity?wsdl")
public class ActivityService
    extends Service
{

    private final static URL ACTIVITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYSERVICE_EXCEPTION;
    private final static QName ACTIVITYSERVICE_QNAME = new QName("http://ws.turismouyapp/schema", "ActivityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8007/ws/activity?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYSERVICE_WSDL_LOCATION = url;
        ACTIVITYSERVICE_EXCEPTION = e;
    }

    public ActivityService() {
        super(__getWsdlLocation(), ACTIVITYSERVICE_QNAME);
    }

    public ActivityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYSERVICE_QNAME, features);
    }

    public ActivityService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYSERVICE_QNAME);
    }

    public ActivityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYSERVICE_QNAME, features);
    }

    public ActivityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActivityPortType
     */
    @WebEndpoint(name = "ActivityPort")
    public ActivityPortType getActivityPort() {
        return super.getPort(new QName("http://ws.turismouyapp/schema", "ActivityPort"), ActivityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActivityPortType
     */
    @WebEndpoint(name = "ActivityPort")
    public ActivityPortType getActivityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.turismouyapp/schema", "ActivityPort"), ActivityPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYSERVICE_EXCEPTION!= null) {
            throw ACTIVITYSERVICE_EXCEPTION;
        }
        return ACTIVITYSERVICE_WSDL_LOCATION;
    }

}
