
package turismouyapp.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "OutingAndInscriptionService", targetNamespace = "http://ws.turismouyapp/schema", wsdlLocation = "http://localhost:8007/ws/outingAndInscription?wsdl")
public class OutingAndInscriptionService
    extends Service
{

    private final static URL OUTINGANDINSCRIPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException OUTINGANDINSCRIPTIONSERVICE_EXCEPTION;
    private final static QName OUTINGANDINSCRIPTIONSERVICE_QNAME = new QName("http://ws.turismouyapp/schema", "OutingAndInscriptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8007/ws/outingAndInscription?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OUTINGANDINSCRIPTIONSERVICE_WSDL_LOCATION = url;
        OUTINGANDINSCRIPTIONSERVICE_EXCEPTION = e;
    }

    public OutingAndInscriptionService() {
        super(__getWsdlLocation(), OUTINGANDINSCRIPTIONSERVICE_QNAME);
    }

    public OutingAndInscriptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OUTINGANDINSCRIPTIONSERVICE_QNAME, features);
    }

    public OutingAndInscriptionService(URL wsdlLocation) {
        super(wsdlLocation, OUTINGANDINSCRIPTIONSERVICE_QNAME);
    }

    public OutingAndInscriptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OUTINGANDINSCRIPTIONSERVICE_QNAME, features);
    }

    public OutingAndInscriptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutingAndInscriptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OutingAndInscriptionPortType
     */
    @WebEndpoint(name = "OutingAndInscriptionPort")
    public OutingAndInscriptionPortType getOutingAndInscriptionPort() {
        return super.getPort(new QName("http://ws.turismouyapp/schema", "OutingAndInscriptionPort"), OutingAndInscriptionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OutingAndInscriptionPortType
     */
    @WebEndpoint(name = "OutingAndInscriptionPort")
    public OutingAndInscriptionPortType getOutingAndInscriptionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.turismouyapp/schema", "OutingAndInscriptionPort"), OutingAndInscriptionPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OUTINGANDINSCRIPTIONSERVICE_EXCEPTION!= null) {
            throw OUTINGANDINSCRIPTIONSERVICE_EXCEPTION;
        }
        return OUTINGANDINSCRIPTIONSERVICE_WSDL_LOCATION;
    }

}
