
package turismouyapp.webservices;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "OutingAndInscriptionPortType", targetNamespace = "http://ws.turismouyapp/schema")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OutingAndInscriptionPortType {


    /**
     * 
     * @param dtInscriptionOuting
     * @param outingName
     * @param userNickname
     * @throws RepeatedInscriptionToTouristOutingException
     */
    @WebMethod
    @RequestWrapper(localName = "inscriptionDataEntry", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.InscriptionDataEntry")
    @ResponseWrapper(localName = "inscriptionDataEntryResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.InscriptionDataEntryResponse")
    @Action(input = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/inscriptionDataEntryRequest", output = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/inscriptionDataEntryResponse", fault = {
        @FaultAction(className = RepeatedInscriptionToTouristOutingException.class, value = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/inscriptionDataEntry/Fault/RepeatedInscriptionToTouristOutingException")
    })
    public void inscriptionDataEntry(
        @WebParam(name = "dtInscriptionOuting", targetNamespace = "")
        DtInscriptionTouristOuting dtInscriptionOuting,
        @WebParam(name = "userNickname", targetNamespace = "")
        String userNickname,
        @WebParam(name = "outingName", targetNamespace = "")
        String outingName)
        throws RepeatedInscriptionToTouristOutingException
    ;

    /**
     * 
     * @param outingName
     * @return
     *     returns java.util.List<turismouyapp.webservices.DtInscriptionTouristOuting>
     */
    @WebMethod
    @WebResult(name = "inscriptions", targetNamespace = "")
    @RequestWrapper(localName = "listOutingInscription", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListOutingInscription")
    @ResponseWrapper(localName = "listOutingInscriptionResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListOutingInscriptionResponse")
    @Action(input = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/listOutingInscriptionRequest", output = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/listOutingInscriptionResponse")
    public List<DtInscriptionTouristOuting> listOutingInscription(
        @WebParam(name = "outingName", targetNamespace = "")
        String outingName);

    /**
     * 
     * @param outingName
     * @return
     *     returns turismouyapp.webservices.DtTouristOuting
     * @throws TouristOutingDoesNotExistException
     */
    @WebMethod
    @WebResult(name = "DtTouristOuting", targetNamespace = "")
    @RequestWrapper(localName = "consultTouristOutingData", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultTouristOutingData")
    @ResponseWrapper(localName = "consultTouristOutingDataResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultTouristOutingDataResponse")
    @Action(input = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/consultTouristOutingDataRequest", output = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/consultTouristOutingDataResponse", fault = {
        @FaultAction(className = TouristOutingDoesNotExistException.class, value = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/consultTouristOutingData/Fault/TouristOutingDoesNotExistException")
    })
    public DtTouristOuting consultTouristOutingData(
        @WebParam(name = "outingName", targetNamespace = "")
        String outingName)
        throws TouristOutingDoesNotExistException
    ;

    /**
     * 
     * @param imageName
     * @param outingName
     */
    @WebMethod
    @RequestWrapper(localName = "updateOutingImageName", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.UpdateOutingImageName")
    @ResponseWrapper(localName = "updateOutingImageNameResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.UpdateOutingImageNameResponse")
    @Action(input = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/updateOutingImageNameRequest", output = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/updateOutingImageNameResponse")
    public void updateOutingImageName(
        @WebParam(name = "outingName", targetNamespace = "")
        String outingName,
        @WebParam(name = "imageName", targetNamespace = "")
        String imageName);

    /**
     * 
     * @param nickname
     * @return
     *     returns java.util.List<turismouyapp.webservices.DtInscriptionTouristOuting>
     */
    @WebMethod
    @WebResult(name = "DtInscriptionTouristOuting", targetNamespace = "")
    @RequestWrapper(localName = "listDtInscriptionTouristOutingByTouristNickname", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListDtInscriptionTouristOutingByTouristNickname")
    @ResponseWrapper(localName = "listDtInscriptionTouristOutingByTouristNicknameResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListDtInscriptionTouristOutingByTouristNicknameResponse")
    @Action(input = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/listDtInscriptionTouristOutingByTouristNicknameRequest", output = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/listDtInscriptionTouristOutingByTouristNicknameResponse")
    public List<DtInscriptionTouristOuting> listDtInscriptionTouristOutingByTouristNickname(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname);

    /**
     * 
     * @param dtTouristOuting
     * @throws RepeatedTouristOutingException
     */
    @WebMethod
    @RequestWrapper(localName = "outingDataEntry", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.OutingDataEntry")
    @ResponseWrapper(localName = "outingDataEntryResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.OutingDataEntryResponse")
    @Action(input = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/outingDataEntryRequest", output = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/outingDataEntryResponse", fault = {
        @FaultAction(className = RepeatedTouristOutingException.class, value = "http://ws.turismouyapp/schema/OutingAndInscriptionPortType/outingDataEntry/Fault/RepeatedTouristOutingException")
    })
    public void outingDataEntry(
        @WebParam(name = "dtTouristOuting", targetNamespace = "")
        DtTouristOuting dtTouristOuting)
        throws RepeatedTouristOutingException
    ;

}
