
package turismouyapp.webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "RepeatedUserEmailFault", targetNamespace = "http://ws.turismouyapp/schema")
public class RepeatedUserEmailException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RepeatedUserEmailFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RepeatedUserEmailException(String message, RepeatedUserEmailFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RepeatedUserEmailException(String message, RepeatedUserEmailFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: turismouyapp.webservices.RepeatedUserEmailFault
     */
    public RepeatedUserEmailFault getFaultInfo() {
        return faultInfo;
    }

}
