
package turismouyapp.webservices;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserPortType", targetNamespace = "http://ws.turismouyapp/schema")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserPortType {


    /**
     * 
     * @param email
     * @return
     *     returns turismouyapp.webservices.DtUser
     */
    @WebMethod
    @WebResult(name = "DtUser", targetNamespace = "")
    @RequestWrapper(localName = "consultUserDataByEmail", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultUserDataByEmail")
    @ResponseWrapper(localName = "consultUserDataByEmailResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultUserDataByEmailResponse")
    @Action(input = "http://ws.turismouyapp/schema/UserPortType/consultUserDataByEmailRequest", output = "http://ws.turismouyapp/schema/UserPortType/consultUserDataByEmailResponse")
    public DtUser consultUserDataByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "confirmRegistration", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConfirmRegistration")
    @ResponseWrapper(localName = "confirmRegistrationResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConfirmRegistrationResponse")
    @Action(input = "http://ws.turismouyapp/schema/UserPortType/confirmRegistrationRequest", output = "http://ws.turismouyapp/schema/UserPortType/confirmRegistrationResponse")
    public void confirmRegistration();

    /**
     * 
     * @param dtUser
     */
    @WebMethod
    @RequestWrapper(localName = "modifyUserData", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ModifyUserData")
    @ResponseWrapper(localName = "modifyUserDataResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ModifyUserDataResponse")
    @Action(input = "http://ws.turismouyapp/schema/UserPortType/modifyUserDataRequest", output = "http://ws.turismouyapp/schema/UserPortType/modifyUserDataResponse")
    public void modifyUserData(
        @WebParam(name = "dtUser", targetNamespace = "")
        DtUser dtUser);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "users", targetNamespace = "")
    @RequestWrapper(localName = "listUsers", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListUsers")
    @ResponseWrapper(localName = "listUsersResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ListUsersResponse")
    @Action(input = "http://ws.turismouyapp/schema/UserPortType/listUsersRequest", output = "http://ws.turismouyapp/schema/UserPortType/listUsersResponse")
    public List<String> listUsers();

    /**
     * 
     * @param nicknameOrEmail
     * @return
     *     returns turismouyapp.webservices.DtUser
     */
    @WebMethod
    @WebResult(name = "DtUser", targetNamespace = "")
    @RequestWrapper(localName = "consultUserData", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultUserData")
    @ResponseWrapper(localName = "consultUserDataResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.ConsultUserDataResponse")
    @Action(input = "http://ws.turismouyapp/schema/UserPortType/consultUserDataRequest", output = "http://ws.turismouyapp/schema/UserPortType/consultUserDataResponse")
    public DtUser consultUserData(
        @WebParam(name = "nicknameOrEmail", targetNamespace = "")
        String nicknameOrEmail);

    /**
     * 
     * @param dtUser
     * @throws RepeatedUserEmailException
     * @throws RepeatedUserNicknameException
     */
    @WebMethod
    @RequestWrapper(localName = "dataEntryUser", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.DataEntryUser")
    @ResponseWrapper(localName = "dataEntryUserResponse", targetNamespace = "http://ws.turismouyapp/schema", className = "turismouyapp.webservices.DataEntryUserResponse")
    @Action(input = "http://ws.turismouyapp/schema/UserPortType/dataEntryUserRequest", output = "http://ws.turismouyapp/schema/UserPortType/dataEntryUserResponse", fault = {
        @FaultAction(className = RepeatedUserEmailException.class, value = "http://ws.turismouyapp/schema/UserPortType/dataEntryUser/Fault/RepeatedUserEmailException"),
        @FaultAction(className = RepeatedUserNicknameException.class, value = "http://ws.turismouyapp/schema/UserPortType/dataEntryUser/Fault/RepeatedUserNicknameException")
    })
    public void dataEntryUser(
        @WebParam(name = "dtUser", targetNamespace = "")
        DtUser dtUser)
        throws RepeatedUserEmailException, RepeatedUserNicknameException
    ;

}
