# Main
main.title = Turismo UY
main.menu.users = Usuarios
main.menu.users.create = Alta Usuario
main.menu.users.consult = Consultar Usuarios
main.menu.users.modify = Modificar Datos Usuario
main.menu.activities = Actividades
main.menu.activities.create = Alta Actividad
main.menu.activities.consult = Consultar Actividad
main.menu.activities.modify = Modificar Actividad
main.menu.activities.ranking = Ranking Actividades
main.menu.outings = Salidas
main.menu.outings.create = Alta Salida
main.menu.outings.consult = Consultar Salida
main.menu.inscriptions = Inscripciones
main.menu.inscriptions.create = Nueva Inscripcion
main.menu.inscriptions.consult = Consultar Inscripciones
main.menu.system = Sistema
main.menu.system.exit = Salir