<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>turismouy.FrontEnd</groupId>
  <artifactId>turismouy.UI</artifactId>
  <version>1.0.0</version>
  <packaging>war</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <ws.server>localhost</ws.server>
    <ws.port>8007</ws.port>
    <jakarta.servlet.version>6.0.0</jakarta.servlet.version>
    <jakarta.servlet.jsp.version>3.1.0</jakarta.servlet.jsp.version>
    <jakarta.el.version>5.0.0</jakarta.el.version>
    <eclipselink.version>4.0.4</eclipselink.version>
    <jakarta.persistence.version>3.1.0</jakarta.persistence.version>
    <hsqldb.version>2.7.2</hsqldb.version>
    <jakarta.servlet.jstl.api.version>3.0.0</jakarta.servlet.jstl.api.version>
    <jakarta.servlet.jstl.version>3.0.1</jakarta.servlet.jstl.version>
    <maven.javadoc.version>3.6.3</maven.javadoc.version>
    <maven.war.version>3.4.0</maven.war.version>
    <common.codecs.version>1.17.0</common.codecs.version>
    <bcrypt.version>0.4</bcrypt.version>
    <jax-ws.version>4.0.3</jax-ws.version>
    <jaxws-plugin.version>3.0.0</jaxws-plugin.version>
    <jakarta.xml.bind.version>4.0.2</jakarta.xml.bind.version>
    <jaxb.runtime.version>4.0.5</jaxb.runtime.version>
    <build-helper-plugin>3.5.0</build-helper-plugin>
    <gson.version>2.13.2</gson.version>
    </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>${jakarta.servlet.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet.jsp</groupId>
      <artifactId>jakarta.servlet.jsp-api</artifactId>
      <version>${jakarta.servlet.jsp.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>jakarta.el</groupId>
      <artifactId>jakarta.el-api</artifactId>
      <version>${jakarta.el.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <version>${jakarta.persistence.version}</version>
      <scope>provided</scope>
    </dependency>
    
    <dependency>
      <groupId>org.eclipse.persistence</groupId>
      <artifactId>eclipselink</artifactId>
      <version>${eclipselink.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet.jsp.jstl</groupId>
      <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
      <version>${jakarta.servlet.jstl.api.version}</version>
    </dependency>

    <dependency>
      <groupId>org.glassfish.web</groupId>
      <artifactId>jakarta.servlet.jsp.jstl</artifactId>
      <version>${jakarta.servlet.jstl.version}</version>
    </dependency>

    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>${common.codecs.version}</version>
    </dependency>

    <dependency>
      <groupId>org.mindrot</groupId>
      <artifactId>jbcrypt</artifactId>
      <version>${bcrypt.version}</version>
    </dependency>

    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>${jax-ws.version}</version>
    </dependency>

    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>${jakarta.xml.bind.version}</version>
    </dependency>

    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>${jaxb.runtime.version}</version>
    </dependency>

	<dependency>
	    <groupId>com.google.code.gson</groupId>
	    <artifactId>gson</artifactId>
	    <version>${gson.version}</version>
	</dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>${maven.war.version}</version>
        <configuration>
          <warName>turismouy.UI</warName>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-maven-plugin</artifactId>
        <version>${jaxws-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>wsimport</goal>
            </goals>
          </execution>
        </executions>
        <configuration>        
	      <wsdlUrls>
	        <wsdlUrl>http://${ws.server}:${ws.port}/ws/user?wsdl</wsdlUrl>
	        <wsdlUrl>http://${ws.server}:${ws.port}/ws/activity?wsdl</wsdlUrl>
	        <wsdlUrl>http://${ws.server}:${ws.port}/ws/outingAndInscription?wsdl</wsdlUrl>
	      </wsdlUrls>
	      <packageName>turismouyapp.webservices</packageName>
	      <keep>true</keep>
	      <sourceDestDir>${project.build.directory}/generated-sources/wsimport</sourceDestDir>
        </configuration>
      </plugin>
      <plugin>
	    <groupId>org.codehaus.mojo</groupId>
	    <artifactId>build-helper-maven-plugin</artifactId>
	    <version>${build-helper-plugin}</version>
	    <executions>
	        <execution>
	            <id>add-source</id>
	            <phase>generate-sources</phase>
	            <goals>
	                <goal>add-source</goal>
	            </goals>
	            <configuration>
	                <sources>
	                    <source>${project.build.directory}/generated-sources/wsimport</source>
	                </sources>
	            </configuration>
	        </execution>
	    </executions>
	  </plugin>
    </plugins>
  </build>
</project>

